# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-29 22:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='lastname',
        ),
    ]
